language: node_js

node_js:
  - "13"
  
services:
- docker

env:
  - CI=true

install:
  - npm install --global mocha
  - npm install -g istanbul
  - npm install

script:
  - ./build.sh
  - npm test

after_success:
  - ./after.sh